// Bütün yazılar bir yerde — носитель языка правит только этот файл
window.L = {
  app: "Derslik Çantam",
  slogan: "Bütün derslikler bir yerde",
  hello: "Selâm!",
  grade: n => n + ({3:"-ünci",4:"-ünci",6:"-ncı",9:"-ncı",10:"-ncı"}[n] || "-nci") + " sınıf",
  gradeWord: "sınıf",
  books: n => n + " derslik",
  search: "Derslik qıdır",
  cont: "Oqumağa devam et",
  page: "saife",
  tabShelf: "Raf",
  tabOffline: "İnternetsiz",
  tabMarks: "Belgiler",
  menu: "Menü",
  close: "Qapat",
  grades: "Sınıflar",
  pickGrade: "Sınıfıñnı sayla",
  change: "Deñiştir",
  lang: "Til",
  langName: "Qırımtatarca",
  help: "Yardım",
  back: "Keri",
  part: p => p + "-nci qısım",
  soon: "Yaqında",
  soonText: "Bu derslik yaqında qoşulacaq.",
  download: "Yükle",
  downloaded: "Yüklendi",
  remove: "Sil",
  addMark: "Belgi qoş",
  delMark: "Belgini sil",
  prev: "Evelki saife",
  next: "Soñraki saife",
  zoomIn: "Büyüt",
  zoomOut: "Kiçilt",
  loading: "Açıla…",
  error: "PDF açılmadı. İnternetni teşkeriñiz.",
  nothing: "Hiç bir şey tapılmadı",
  offlineEmpty: "Yüklengen derslik yoq",
  marksEmpty: "Belgi yoq",
  install: "Ekranğa qoş",
  installIos: "Safari: «Поделиться» → «На экран Домой»",
  helpText: [
    "Sınıfıñnı sayla, derslikni aç ve oqu.",
    "«Yükle» — internetsiz oqumaq içün.",
    "Belgi — kerekli saifeni saqla."
  ]
};
