// Bütün yazılar bir yerde — носитель языка правит только этот файл
window.L = {
  app: "Derslik Çantam",
  slogan: "Bütün derslikler bir yerde",
  hello: "Selâm",
  grade: n => n + ({3:"-ünci",4:"-ünci",6:"-ncı",9:"-ncı",10:"-ncı"}[n] || "-nci") + " sınıf",
  cls: (g, l) => g + (l ? "-" + l : "") + " sınıf",
  gradeWord: "sınıf", gradeLbl: "Sınıf",
  books: n => n + " derslik",
  part: p => p + "-nci qısım",
  search: "Derslik qıdır",
  cont: "Oqumağa devam et",
  page: "saife",
  tabShelf: "Raf", tabOffline: "İnternetsiz", tabMarks: "Belgiler",
  menu: "Menü", close: "Qapat", grades: "Sınıflar", change: "Deñiştir",
  lang: "Til", langName: "Qırımtatarca", help: "Yardım", back: "Keri",
  soonText: "Bu sınıf içün derslik daa qoşulmağan.",
  download: "Yükle", downloaded: "Yüklendi", remove: "Sil",
  addMark: "Belgi qoş", delMark: "Belgini sil",
  prev: "Evelki saife", next: "Soñraki saife", zoomIn: "Büyüt", zoomOut: "Kiçilt",
  loading: "Açıla…", error: "Açılmadı. İnternetni teşkeriñiz.",
  nothing: "Hiç bir şey tapılmadı", offlineEmpty: "Yüklengen derslik yoq", marksEmpty: "Belgi yoq",
  install: "Ekranğa qoş", installIos: "Safari: «Поделиться» → «На экран Домой»",
  installText: "Uyğulama kibi açılır ve internetsiz de işler", installBtn: "Nasıl?",
  iosSafariSteps: ["Safari-de aşağıdaki (iPad-de yuqarıdaki) [share] «Поделиться» düğmesine basıñız", "Menüni aşağı çekip «На экран Домой» saylañız", "Yuqarıda «Добавить» basıñız — ekranda «Çantam» belgisi peyda olur"],
  iosChromeSteps: ["Chrome-da adres satırında [share] «Поделиться» düğmesine basıñız", "«На экран Домой» saylañız", "«Добавить» basıñız — ekranda «Çantam» belgisi peyda olur"],
  otherSteps: ["Brauzer menüsini açıñız (⋮ ya da ⋯)", "«Установить приложение» ya da «Добавить на главный экран» saylañız", "Tasdıqlañız — ekranda «Çantam» belgisi peyda olur"],
  guide: [
    ["book", "Derslikni oqumaq", ["Raf bölüminde derslikniñ qapağına basıñız", "Saifelerni barmaq ile solğa-sağğa sürtip ya da ‹ › düğmeleri ile çeviriñiz", "Aşağıdaki çizgi ile kerekli saifege tez keçip olasıñız", "Planşetni yatqızsañız, eki saife yan-yana — kitap kibi açılır"]],
    ["down", "İnternetsiz oqumaq", ["Derslikni açıñız", "Yuqarıda «Yükle» belgisine basıñız", "Qapaqta ✓ belgisi peyda olsa — derslik telefonda saqlandı", "Endi internet olmasa da açılır. Bu derslikler «İnternetsiz» bölüminde"]],
    ["mark", "Belgiler", ["Kerekli saifede yuqarıdaki belgi düğmesine basıñız", "«Belgiler» bölüminden o saifege bir basmaq ile qaytıñız", "Belgiler tek bu telefonda saqlana"]],
    ["user", "Profil ve parol", ["«Profil» bölüminde adıñız, mektebiñiz ve sınıfıñız körüne", "Yañlış olsa — «Maalümatnı tüzet» basıñız, idareci tasdıqlar", "Parolnı deñiştirmek içün — «Parolnı deñiştir», idareci tasdıqlağan soñ yañı parol işler"]],
    ["help", "Bir şey işlemese", ["Uyğulamanı qapatıp, yañıdan açıñız (bazıda eki kere)", "Kompyuterde Ctrl+Shift+R basıñız", "Yañı derslikler bir-eki daqiqadan soñ peyda ola", "Yardım kerek olsa — ocañızğa ya da idarecige muracaat etiñiz"]]
  ],
  helpText: ["Dersligiñni aç ve oqu.", "«Yükle» — internetsiz oqumaq içün.", "Belgi — kerekli saifeni saqla."],

  // Kiriş ve qayd
  login: "Kiriş", doLogin: "Kir", register: "Qayd ol", logout: "Çıq",
  noAcc: "Hesabıñız yoqmı?", haveAcc: "Hesabıñız barmı?",
  iAm: "Kimsiñiz?", cabinet: "İdare kabineti",
  school: "Mektep", pickSchool: "Mektebiñizni saylañız", errSchool: "Mektebiñizni saylañız",
  profile: "Profil", profileHint: "Sınıf ya da mektep yañlış olsa, ocañızğa ya da idarecige aytıñız.",
  passSent: "Arıza yiberildi. İdareci tasdıqlağan soñ yañı parol işlep başlar.", passChanged: "Parol deñiştirildi",
  pwReq: "yañı parol", fixTag: "tüzetüv", was: "evelki",
  fixReq: "Maalümatnı tüzet", fixHint: "Deñişiklik idareci tasdıqlağan soñ körünir.", fixSent: "Arıza yiberildi. İdareci tasdıqlağan soñ deñişir.",
  sendApp: "Arıza yiber",
  bookTitle: "Kitap adı", bookTitleHint: "Talebe raf üzerinde bu adnı körer. Boş olsa — dersniñ adı.",
  cover: "Qapaq resmi", coverHint: "Bağlantı qoyuñız ya da resim faylını saylañız", coverDel: "Qapaqnı sil",
  coverLinkOnly: "Resim saytqa saqlanmadı, bağlantı olaraq qaldı (internetsiz körünmez). Faylnı saylap olasıñız.", errFill: "Bütün saalarnı toldurıñız",
  schools: "Mektepler", addSchool: "Mektep qoş", schoolNameLbl: "Mektep adı", allSchools: "Bütün mektepler",
  newYear: "Yañı oquv yılı", newYearText: (n, m) => n + " talebe bir sınıf yuqarı keçer, " + m + " talebe mezun olur (11-nci sınıf).",
  delGrads: "Mezunlarnı sil", newYearDone: (n, m) => n + " talebe keçirildi, " + m + " mezun",
  firstLogin: "İlk kiriş", firstText: "Muvaqqat parolnı deñiştiriñiz ve GitHub tokenini qoşuñız.",
  newPass: "Yañı parol", oldPass: "Eski parol", changePass: "Parolnı deñiştir",
  notAdmin: "Bu kabinet tek idareci içün", toApp: "Uyğulamağa keç",
  username: "Login", password: "Parol", password2: "Parolnı tekrarlañız",
  name: "Adıñız", surname: "Soyadıñız", letter: "Harf",
  usernameHint: "Latin arifleri ve raqamlar, meselâ ali.5a",
  makeApp: "Arıza yarat",
  errLogin: "Login ya da parol doğru degil",
  errNoUser: "Bu login tapılmadı. Arızañız tasdıqlanğanmı?",
  errPass2: "Parollar bir degil",
  errPassLen: "Parol eñ az 8 işaret olmalı",
  errUser: "Login: eñ az 3 işaret, latin arifleri ve raqamlar",
  errTaken: "Bu login meşğul, başqasını saylañız",
  errNet: "İnternet yoq",
  appReady: "Arızañız azır",
  appSend: "Bu QR-kodnı ocañızğa ya da idarecige kösteriñiz. O, telefonınıñ kamerası ile skanerlep tasdıqlar.",
  appShare: "Telegram / WhatsApp ile yiber",
  copy: "Kopiyala", copied: "Kopiyalandı",
  appAfter: "Tasdıqlanğan soñ derslikleriñiz özü açılacaq",
  appSent: "Arızañız idarecige yiberildi",
  appSentText: "İdareci tasdıqlağan soñ derslikleriñiz bu ekranda özü açılacaq.",
  appNotSent: "Arıza avtomatik yiberilmedi. Bu kodnı idarecige kösteriñiz ya da kopiyalap yiberiñiz.",
  reqToken: "Arıza tokeni (Issues)", reqTokenHint: "Tek Issues: Read and write. Talebeler arızanı bu token ile avtomatik yibereler.",
  appCancel: "Arızanı lâğu et",
  shareText: n => "Derslik Çantam: " + n + " qayd olmaq istey",
  wiped: "Hesabıñız qapatıldı. İdareciñizge muracaat etiñiz.",

  // Qurulış
  setup: "Qurulış: idareci hesabı", setupText: "Bu ekran tek bir kere, ilk açılışta körünir. İdareci (siz) hesabını yaratıñız. Soñ bu yerde Kiriş ekranı olacaq.",
  token: "GitHub token", tokenHint: "Contents: Read and write, tek bu repo içün",
  repo: "Repo", setupDo: "Qur", setupDone: "Azır! Bir daqiqadan soñ sayt yañılanır.",

  // İdare
  admin: "İdare",
  apps: "Arızalar", students: "Talebeler", booksAdm: "Derslikler", settings: "Sazlamalar",
  approve: "Tasdıqla", reject: "Red et", block: "Blokla", del: "Sil", save: "Saqla", cancel: "Lâğu et",
  role: "Rol", roles: { student: "Talebe", teacher: "Oca", admin: "İdareci" },
  noApps: "Yañı arıza yoq. Talebeniñ yibergen bağlantısını açıñız ya da kodnı bu yerge qoyuñız.",
  pasteCode: "Arıza kodu ya da bağlantı", addApp: "Qoş", badCode: "Kod doğru degil",
  replaceUser: "Bu login bar. Yañı parol ile deñiştirilsinmi?",
  allClasses: "Bütün sınıflar",
  moveClass: "Sınıfnı keçir", from: "Nereden", to: "Nereye",
  subject: "Ders", author: "Müellif", partLbl: "Qısım", file: "PDF fayl", addBook: "Derslik qoş",
  saving: "Saqlana…", uploading: "Yüklene…", encrypting: "Şifrelene…", saved: "Saqlandı", confirmDel: "Silinsinmi?",
  blockText: "Talebe silinir, sınıfnıñ açarı yañılanır.",
  tooBig: "Fayl 150 MB-tan büyük",
  needToken: "Evelâ Sazlamalarda GitHub token yazıñız",
  tokenBad: "Token ya da repo doğru degil",
  tokenOk: "Bağlantı yahşı",
  check: "Teşker",
  deploying: "Deñişiklikler bir daqiqadan soñ talebelerde körünir",
  moved: n => n + " talebe keçirildi"
};

window.SUBJECTS = {
  mat: "Matematika", alg: "Algebra", geo: "Geometriya", rus: "Rus tili", crh: "Qırımtatar tili",
  oqu: "Edebiy oquv", edb: "Edebiyat", crhedb: "Qırımtatar edebiyatı", etr: "Etraf dünya", eng: "İngliz tili",
  tar: "Tarih", bio: "Biologiya", cog: "Coğrafiya", fiz: "Fizika", kim: "Kimya", inf: "İnformatika"
};
window.LETTERS = ["A", "B", "V", "G", "D"];
